//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crosser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crosser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream car {
            get {
                return ResourceManager.GetStream("car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap car_crash_clipart {
            get {
                object obj = ResourceManager.GetObject("car_crash_clipart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;leaderboard&gt;
        ///  &lt;highscore&gt;
        ///    &lt;nickname&gt;Speedy&lt;/nickname&gt;
        ///    &lt;score&gt; 22&lt;/score&gt;
        ///  &lt;/highscore&gt;
        ///  &lt;highscore&gt;
        ///    &lt;nickname&gt;Scooter&lt;/nickname&gt;
        ///    &lt;score&gt;18&lt;/score&gt;
        ///  &lt;/highscore&gt;
        ///  &lt;highscore&gt;
        ///    &lt;nickname&gt;Superfast&lt;/nickname&gt;
        ///    &lt;score&gt;19&lt;/score&gt;
        ///  &lt;/highscore&gt;
        ///  &lt;highscore&gt;
        ///    &lt;nickname&gt;Slick&lt;/nickname&gt;
        ///    &lt;score&gt;25&lt;/score&gt;
        ///  &lt;/highscore&gt;
        ///  &lt;highscore&gt;
        ///    &lt;nickname&gt;Skid&lt;/nickname&gt;
        ///    &lt;score&gt;50&lt;/score&gt;
        ///  &lt;/highscore&gt;
        ///&lt;/leaderboard&gt;.
        /// </summary>
        internal static string leaderboard {
            get {
                return ResourceManager.GetString("leaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap output_onlinepngtools__1___1_ {
            get {
                object obj = ResourceManager.GetObject("output_onlinepngtools__1___1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream skidcrash {
            get {
                return ResourceManager.GetStream("skidcrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Traffic_Light {
            get {
                object obj = ResourceManager.GetObject("Traffic_Light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream traffichorns {
            get {
                return ResourceManager.GetStream("traffichorns", resourceCulture);
            }
        }
    }
}
